name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.4.1 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    container:
      image: barichello/godot-ci:4.4.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment for templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          mkdir -p /home/runner/.local/share/godot/export_templates/${GODOT_VERSION}.stable/

      - name: Install web export templates
        run: |
          echo "Downloading Godot ${GODOT_VERSION} export templates..."
          curl -Lo /tmp/templates.tpz https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          echo "Extracting templates..."
          cd /tmp && unzip -q templates.tpz
          
          # Copy web template files and create specific debug and release files Godot expects
          echo "Installing web templates..."
          cp -v /tmp/templates/web_template.zip ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          cp -v /tmp/templates/web_template.zip ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/web_nothreads_debug.zip
          cp -v /tmp/templates/web_template.zip ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/web_nothreads_release.zip
          
          # Copy to other potential location for redundancy
          cp -v /tmp/templates/web_template.zip /home/runner/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          cp -v /tmp/templates/web_template.zip /home/runner/.local/share/godot/export_templates/${GODOT_VERSION}.stable/web_nothreads_debug.zip
          cp -v /tmp/templates/web_template.zip /home/runner/.local/share/godot/export_templates/${GODOT_VERSION}.stable/web_nothreads_release.zip
          
          echo "Verifying installed templates:"
          find /home/runner ~/.local -name "*.zip" | grep godot
          
      - name: Import project resources
        run: |
          echo "Importing project resources..."
          mkdir -p .godot/imported/
          godot --headless --quit
          ls -la .godot/imported/ || echo "No imported resources directory"
          
      - name: Create staging directory
        run: mkdir -v -p docs

      - name: Build
        run: godot --headless --export-release "Web" docs/index.html

      - name: Copy additional files to build directory
        run: |
          cp coi-serviceworker.js docs/ || echo "coi-serviceworker.js not found"
          ls -la docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
