name: Export Godot Web Build

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache Godot
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/**
            /usr/local/bin/godot
            ~/.config/godot/**
          key: ubuntu22.04-godot-4.4.1

      - name: Download Godot export templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          unzip Godot_v4.4.1-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.4.1.stable

      - name: Import Godot resources
        run: godot --headless --editor --quit --path .

      - name: Export project
        run: godot --headless --export-release "Web" ./build/index.html

      - name: Copy coi-serviceworker.js
        run: cp coi-serviceworker.js docs/

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git commit -m "Automated web export"
          git push
